collections:
  posts:
    output: true
    permalink: /posts/:slug
  archives:
    output: true
  projects:
    output: true
    permalink: /portfolio/:slug

# This is for CloudCannon options 

# This is to set collections

collections:
  posts:
    output: true
    permalink: /posts/:slug
  archives:
    output: true

# This is for CloudCannon options 

_select_data:
  background-colors:
    bg-sage-200: Light Background
    bg-sage-500: Dark Background
    bg-white: White Background
  grid-sizes:
    grid-cols-1: 1 Column
    grid-cols-2: 2 Columns
    grid-cols-3: 3 Columns
    grid-cols-4: 4 Columns
  image-positions:
    left: Left
    right: Right
  widths:
    container: Container
    w-full: Full-Width
  col-sizes:
    col-span-1: 1 Column
    col-span-2: 2 Columns  
    col-span-3: 3 Columns  
    col-span-4: 4 Columns    

# This is for Page blocks

page_blocks: []

_array_structures:
  page_blocks:
