collections:
  posts:
    output: true
    permalink: /posts/:slug
  archives:
    output: true
  projects:
    output: true
    permalink: /portfolio/:slug


assets:
   sources:
       -assets/fonts

# This is for CloudCannon options 

_select_data:
  background-colors:
    bg-sage-200: Light Background
    bg-sage-500: Dark Background
    bg-white: White Background
  grid-sizes:
    grid-cols-1: 1 Column
    grid-cols-2: 2 Columns
    grid-cols-3: 3 Columns
    grid-cols-4: 4 Columns
  image-positions:
    left: Left
    right: Right
  widths:
    container: Container
    w-full: Full-Width
  col-sizes:
    col-span-1: 1 Column
    col-span-2: 2 Columns  
    col-span-3: 3 Columns  
    col-span-4: 4 Columns
  gallery-sizes:
    col-span-4 md:col-span-3: Landscape
    col-span-4 md:col-span-2: Portrait 1/2
    col-span-4 md:col-span-3: Portrait 1/3
  type:
    recommendation: Recommendation
    text: Text  


# This is for Page blocks

page_blocks: []

_array_structures:
  page_blocks:
    - label: Portfolio Content
      icon: article
      value:    
        _id: portfolio-content
        title: Portfolio Content
        grid-size: md:grid-cols-2
        background-color: bg-white
        width: container
        overlap:
        padding-top: pt-20
        padding-bottom: pb-20
        columns:
          - _type: image
            image: /assets/images/elsewhere_blog_hoi_an.jpg
            col-size: col-span-1
          - _type: text
            description-html: Lorem ipsum dolor sit
            col-size: col-span-1
    - label: Blog Content
      icon: article
      value:    
        _id: blog-content
        headline: Lorem Ipsum
        type: Recommendation
        recommended:
          - title: Combo Milano
            url: https://thisiscombo.com/de/location/milano/
            description-html: "The hostel is located in Navigli (read more below), with a lot of bars and restaurants just around the corner."

  columns:
    - label: Image
      icon: photo_camera
      value:    
        _type: image
        image:
        col-size: 
    - label: Text
      icon: description
      value:    
        _type: text
        title: text
        description-html: Lorem ipsum dolor sit amet
        col-size:              