# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Jekyll

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  data:
    path: _data
    output: false
  posts:
    path: _posts
    icon: 
    output: true
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
  pages:
    path: ''
    output: true
    filter: strict
  archives:
    output: true
    path: _archives
  projects:
    output: true
    path: _projects

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: _data
  collections: ''
  layouts: _layouts
  static: ''
  uploads: uploads
  includes: _includes
  dam_uploads: ''
  dam_static: ''

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC

# Input configuration video
_inputs:
  author:
    type: select
    comment: "The author of this post"
    label: Author Name
  layout:
    type: select
    label: Layout

_select_data:
  authors:
  - Tara
  - Otto
  - Lio
 layouts:
    default: Default
    lookbook-layout: Lookbook
  background-colors:
    bg-black: Dark Background
    bg-white: White Background
  image-positions:
    left: Left
    right: Right
  widths:
    container: Container
    w-full: Full-Width
  positions:
    items-start: Top
    items-center: Center  
    items-end: Bottom      
  col-sizes:
    col-span-4 lg:col-span-2: 2 Columns / Mobile 4 Columns
    col-span-4 lg:col-span-3 lg:row-span-1: 3 Columns / Mobile 4 Columns
    col-span-6 lg:col-span-3 lg:row-span-1: 3 Columns / Mobile 6 Columns
    col-span-12 lg:col-span-3 lg:row-span-1: 3 Columns / Mobile Full Width
    col-span-4: 4 Columns
    col-span-6: 6 Columns 
    col-span-4 lg:col-span-6: 6 Columns / Mobile 4 Columns
    col-span-12 lg:col-span-6: 6 Columns / Mobile Full Width
    col-span-4 lg:col-span-6 lg:row-span-2: 6 Columns / 2 Rows / Mobile 4 Columns
    col-span-6 lg:row-span-2: 6 Columns / 2 Rows
    col-span-8: 8 Columns
    col-span-8 lg:col-span-6 : 8 Columns / Mobile 6 Columns
    col-span-12: Full width
