seo: 
  site_name: Tara Otto | Design & Travel
  title: Tara Otto | Design & Travel
  description: Design Portfolio and Travel Blog of Tara Otto
  keywords: design, brand design, logo design, web design, web development, travel, blog, tara hunka, tara otto, of elsewhere
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_url: 
  pinterest_url: