seo: 
  site_name: Of Elsewhere
  title: Of Elsewhere
  description: Design Portfolio and Travel Blog of Tara Hunka
  keywords: design, brand design, logo design, web design, web development, travel, blog, tara hunka, tara otto, of elsewhere
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_url: 
  pinterest_url: